/* Bundled list of major world cities for the City autocomplete field. */
const WORLD_CITIES = [
"Tokyo","Delhi","Shanghai","Sao Paulo","Mexico City","Cairo","Mumbai","Beijing","Dhaka","Osaka",
"New York","Karachi","Buenos Aires","Chongqing","Istanbul","Kolkata","Manila","Lagos","Rio de Janeiro","Tianjin",
"Kinshasa","Guangzhou","Los Angeles","Moscow","Shenzhen","Lahore","Bangalore","Paris","Bogota","Jakarta",
"Chennai","Lima","Bangkok","Seoul","Nagoya","Hyderabad","London","Tehran","Chicago","Chengdu",
"Nanjing","Wuhan","Ho Chi Minh City","Luanda","Ahmedabad","Kuala Lumpur","Xi'an","Hong Kong","Dongguan","Hangzhou",
"Foshan","Shenyang","Riyadh","Baghdad","Santiago","Surat","Madrid","Suzhou","Pune","Harbin",
"Houston","Dallas","Toronto","Dar es Salaam","Miami","Belo Horizonte","Singapore","Philadelphia","Atlanta","Fukuoka",
"Khartoum","Barcelona","Johannesburg","Saint Petersburg","Qingdao","Dalian","Washington","Yangon","Alexandria","Guadalajara",
"Ankara","Chittagong","Addis Ababa","Melbourne","Nairobi","Sydney","Kabul","Amman","Taipei","Cape Town",
"Jeddah","Casablanca","Berlin","Monterrey","Kano","Abidjan","Havana","Kuwait City","Rome","Montreal",
"Baku","Zhengzhou","Changsha","Kyiv","Milan","Xiamen","Nanning","Tel Aviv","Jinan","Vancouver",
"Athens","Doha","Auckland","Brisbane","Vienna","Warsaw","Budapest","Prague","Dublin","Copenhagen",
"Stockholm","Oslo","Helsinki","Zurich","Geneva","Amsterdam","Rotterdam","Brussels","Lisbon","Porto",
"Munich","Frankfurt","Hamburg","Cologne","Stuttgart","Dusseldorf","Leipzig","Nice","Lyon","Marseille",
"Toulouse","Bordeaux","Nantes","Strasbourg","Edinburgh","Glasgow","Manchester","Birmingham","Liverpool","Leeds",
"Bristol","Cardiff","Belfast","Barcelona","Valencia","Seville","Bilbao","Malaga","Naples","Turin",
"Florence","Venice","Bologna","Palermo","Zagreb","Belgrade","Bucharest","Sofia","Bratislava","Ljubljana",
"Vilnius","Riga","Tallinn","Reykjavik","Luxembourg","Monaco","Krakow","Gdansk","Wroclaw","Poznan",
"Thessaloniki","Porto Alegre","Brasilia","Salvador","Fortaleza","Curitiba","Recife","Manaus","Belem","Goiania",
"Montevideo","Asuncion","La Paz","Quito","Guayaquil","Caracas","Medellin","Cali","Panama City","San Jose",
"San Salvador","Tegucigalpa","Managua","Guatemala City","Santo Domingo","San Juan","Kingston","Port-au-Prince","Nassau","Bridgetown",
"Ottawa","Calgary","Edmonton","Winnipeg","Quebec City","Halifax","Victoria","San Francisco","San Diego","San Antonio",
"Austin","San Jose","Jacksonville","Columbus","Charlotte","Indianapolis","Seattle","Denver","Boston","Nashville",
"Detroit","Portland","Memphis","Oklahoma City","Las Vegas","Louisville","Baltimore","Milwaukee","Albuquerque","Tucson",
"Fresno","Sacramento","Kansas City","Mesa","Omaha","Raleigh","Minneapolis","Tulsa","Cleveland","New Orleans",
"Honolulu","Anchorage","Orlando","Pittsburgh","Cincinnati","St. Louis","Salt Lake City","Richmond","Buffalo","Tampa",
"Osaka","Sapporo","Kobe","Kyoto","Kawasaki","Saitama","Hiroshima","Sendai","Kitakyushu","Chiba",
"Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Jeju City","Guiyang","Kunming",
"Nanchang","Hefei","Fuzhou","Shijiazhuang","Changchun","Urumqi","Lhasa","Lanzhou","Xining","Yinchuan",
"Macau","Ulaanbaatar","Vientiane","Phnom Penh","Naypyidaw","Colombo","Kathmandu","Thimphu","Male","Islamabad",
"Peshawar","Faisalabad","Multan","Rawalpindi","Quetta","Chandigarh","Jaipur","Lucknow","Kanpur","Nagpur",
"Indore","Bhopal","Patna","Vadodara","Coimbatore","Kochi","Visakhapatnam","Thiruvananthapuram","Amritsar","Varanasi",
"Ranchi","Guwahati","Chandigarh","Mysore","Nasik","Rajkot","Agra","Meerut","Ludhiana","Srinagar",
"Muscat","Manama","Abu Dhabi","Dubai","Sharjah","Beirut","Damascus","Aleppo","Sana'a","Aden",
"Mecca","Medina","Dammam","Tabuk","Basra","Erbil","Mosul","Tripoli","Benghazi","Tunis",
"Algiers","Oran","Rabat","Marrakech","Fez","Tangier","Nouakchott","Bamako","Ouagadougou","Niamey",
"Dakar","Conakry","Freetown","Monrovia","Accra","Lome","Cotonou","Yaounde","Douala","Libreville",
"Brazzaville","Bangui","Ndjamena","Djibouti","Mogadishu","Kampala","Kigali","Bujumbura","Lusaka","Harare",
"Gaborone","Windhoek","Maputo","Antananarivo","Port Louis","Victoria","Lilongwe","Blantyre","Pretoria","Durban",
"Port Elizabeth","Bloemfontein","Maseru","Mbabane","Kolkata","Perth","Adelaide","Canberra","Hobart","Darwin",
"Gold Coast","Newcastle","Wellington","Christchurch","Hamilton","Dunedin","Suva","Port Moresby","Noumea","Papeete"
];
